### ISSUE TITLE
ZRFC gives error /SIE/PD_DS_BO_BOOKMARKS while activating

### ISSUE THREAD

**Issue by SMG1985** [Aashish28/ABAP#1]
Type "/SIE/PD_DS_BO_BOOKMARKS" is unknown

**Comment by Aashish28** [comment]
This is plain ABAP structure "/SIE/PD_DS_BO_BOOKMARKS" created via SE11 and having below fields. You can create it with any Z/Y name.
 
'id' as integer
'cuid'  as guid
'type' as string
'name' as string
'description' as string
